# Generated by Django 5.0.1 on 2024-02-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_habit_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='life_points',
            field=models.IntegerField(default=0),
        ),
    ]
