# Generated by Django 5.0.1 on 2024-02-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_habit_points_user_life_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='life_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
