# Generated by Django 5.0.1 on 2024-02-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='habit',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='habits', to='api.category'),
        ),
    ]
