# Generated by Django 5.0.1 on 2024-03-31 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_main_content_color_user_navbar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_content_color',
            field=models.CharField(default='#8bc34a', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='navbar_color',
            field=models.CharField(default='#4caf50', max_length=7),
        ),
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('current_exp', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
